spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco_da_esteira
    username: root
    password: Flavinha0@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

spotify:
  client-id: c6ded4fe45494a83ad63bb28a654897b
  client-secret: 8f40feea75f24b2aa67513af23faed15
  redirect-uri: http://localhost:8080/api/user/callback
  response-type: code
  state: state
  scope: user-read-private user-read-email user-library-read user-library-modify